server:
  port: 3030
spring:
  datasource:
    url: jdbc:mysql://39.97.212.229:3307/covid?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 0
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8